# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5291fc3fbb85418792a99e3882e30c78b8b597efbf3e633616927030e3c48548bc114500d6ee5aa5ab0394df6e8e0bbec59f4a57e3c0beecaa5c6f56fc61888b

test:
  secret_key_base: 4ff5a79530edf04a4eb168d00e83b6ea2f095f788e0d88d1dc507101c41ad95cb3a7e4a8c49c2a6cf5ebeecb2a19d90b963e36604d645723985ad6f9864bb775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
